# Adapted from https://github.com/TYPO3GmbH/blog/blob/master/.github/workflows/ci.yml
name: CI

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        typo3: [^10.4, ^11.5]
        php: ['7.4']
        include:
        - typo3: ^11.5
          php: '8.0'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP ${{ matrix.php }}, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, dom, zip, mysql

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
      run: |
        composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
        git checkout composer.json

    - name: php-cs-fixer
      run: composer ci:php:fixer

    - name: Lint PHP
      run: composer ci:php:lint

  # Target files will be overwritten
  minify:
    needs: code-quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Minify CSS with Web minifier
      uses: zugazagoitia/minify-js@v0.2
      with:
        directory: 'Build/Css/LikeIt.css'
        output: 'Resources/Public/Css/'

    - name: Minify JavaScript with Web minifier
      uses: zugazagoitia/minify-js@v0.2
      with:
        directory: 'Build/JavaScript/LikeIt.js'
        output: 'Resources/Public/JavaScript/'

    - name: Auto committing minified CSS/JS files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
